### ISSUE TITLE
How to add named imports?

### ISSUE THREAD

**Issue by Stupidism** [Rulexec/vscode-custom-autoimport#1]
import { useEffect, useMemo } from 'react';

**Comment by Rulexec** [comment]
There is no such feature right now, but I will try to implement it today.

Thanks for the first issue ;)

Sorry for too long reply, situation in Belarus is not conducive to work.

**Comment by Rulexec** [comment]
Done. Now in settings you can specify:

```
"{ useEffect }": "react",
"{ useMemo }": "react",
```

**UPD:** Added support for:

```
"{ useEffect, useMemo }": "react",
```

It will add suggestions for `useEffect` and `useMemo`.
